# Generated by Django 2.2.1 on 2019-07-22 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('attr_name', models.CharField(max_length=100, verbose_name='Attribute Name')),
                ('classifier', models.CharField(max_length=100, verbose_name='Classifier')),
                ('predicted_class', models.CharField(max_length=100, verbose_name='Predicted Class')),
                ('class_confidence', models.FloatField(verbose_name='Class Confidence')),
                ('confidence_str', models.CharField(max_length=100, verbose_name='Confidence String')),
                ('attr_categories', models.TextField(verbose_name='Attribute Categories')),
                ('category_desc', models.TextField(verbose_name='Category Descriptions')),
                ('attr_values', models.TextField(verbose_name='Attribute Values')),
                ('explanations', models.TextField(verbose_name='Explanations')),
                ('global_explanations', models.TextField(verbose_name='Global Explanations')),
                ('is_current', models.BooleanField(verbose_name='Is Current')),
                ('extra_info', models.TextField(default='', verbose_name='Extra Info')),
            ],
        ),
        migrations.CreateModel(
            name='ServedTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_ids', models.CharField(max_length=10000, validators=[django.core.validators.int_list_validator])),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('tweet', models.TextField()),
                ('is_active', models.BooleanField()),
                ('update_version', models.IntegerField()),
                ('gender_lex_score', models.FloatField()),
                ('gender_lex_words', models.TextField()),
                ('gender_lex_weights', models.TextField()),
                ('age_lex_score', models.FloatField()),
                ('age_lex_words', models.TextField()),
                ('age_lex_weights', models.TextField()),
                ('sentiment_lex_score', models.FloatField()),
                ('sentiment_lex_words', models.TextField()),
                ('sentiment_lex_weights', models.TextField()),
                ('polarity_score', models.FloatField(default=0.0)),
                ('polarity_words', models.TextField(default='')),
                ('polarity_weights', models.TextField(default='')),
                ('sentiment_blob_nbc', models.FloatField(default=0.0)),
                ('subjectivity_score', models.FloatField(default=0.0)),
                ('subjectivity_words', models.TextField(default='')),
                ('subjectivity_weights', models.TextField(default='')),
            ],
        ),
    ]
