# Generated by Django 2.2.1 on 2019-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='origin',
            field=models.TextField(default='original'),
        ),
    ]
