# Generated by Django 2.2.1 on 2019-07-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20190724_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='income_score',
            field=models.FloatField(default=0.0),
        ),
    ]
