# Generated by Django 2.2.1 on 2019-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_tweet_income_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='age_translation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tweet',
            name='gender_translation',
            field=models.TextField(default=''),
        ),
    ]
