# Generated by Django 2.2.1 on 2019-07-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20190730_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='age_translation',
            new_name='age_translation_o_y',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='gender_translation',
            new_name='age_translation_y_o',
        ),
        migrations.AddField(
            model_name='tweet',
            name='gender_translation_f_m',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tweet',
            name='gender_translation_m_f',
            field=models.TextField(default=''),
        ),
    ]
