# Generated by Django 2.2.3 on 2019-08-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20190730_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='edu_gr_score',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='edu_hs_score',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='edu_ug_score',
            field=models.FloatField(default=-1.0),
        ),
    ]
