# Generated by Django 2.2.3 on 2019-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_tweet_nn_r_income_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='inc_above_score',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='inc_below_score',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='inc_highest_score',
            field=models.FloatField(default=-1.0),
        ),
    ]
